name: multirescnn
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - _pytorch_select=0.1=cpu_0
  - blas=1.0
  - ca-certificates
  - debugpy=1.5.1
  - docopt=0.6.2
  - freetype=2.10.4
  - gitdb=4.0.9
  - gitpython=3.1.27
  - importlib_metadata
  - intel-openmp=2021.3.0
  - jpeg=9d
  - lcms2=2.12
  - libffi=3.3
  - libpng=1.6.37
  - libtiff=4.2.0
  - libuv=1.40.0
  - libwebp-base=1.2.0
  - lz4-c
  - mkl=2021.3.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.2
  - munch=2.5.0
  - ncurses=6.2
  - ninja=1.10.2
  - numpy=1.20.3
  - numpy-base
  - olefile
  - openjpeg
  - openssl
  - pillow
  - pip
  - py-cpuinfo
  - pymongo=3.10.1
  - python=3.7.11
  - python_abi=3.7
  - pytorch=1.7.1
  - readline=8.1
  - sacred=0.8.2
  - seml=0.3.5
  - setuptools
  - smmap=3.0.5
  - sqlite=3.36.0
  - tk=8.6.10
  - torchaudio=0.7.2
  - torchvision=0.8.2
  - typing_extensions
  - wheel=0.37.0
  - wrapt=1.12.1
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - alabaster
    - cython
    - docutils==0.14
    - editdistance==0.5.3
    - elasticsearch==7.0.2
    - elmoformanylangs==0.0.2
    - fasttext==0.9.2
    - flask==1.0.3
    - flask-cors==3.0.8
    - gensim==3.7.3
    - gevent==1.4.0
    - greenlet==0.4.15
    - h5py==2.9.0
    - idna==2.8
    - json-lines==0.5.0
    - jsonlines==2.0.0
    - jsonnet==0.13.0
    - jsonschema==3.0.1
    - kiwisolver==1.1.0
    - langdetect==1.0.7
    - lxml==4.3.3
    - markupsafe==1.1.1
    - marshmallow==2.6.1
    - marshmallow-jsonapi==0.15.1
    - matplotlib==3.1.0
    - more-itertools==7.0.0
    - murmurhash==1.0.2
    - nltk==3.4.3
    - nmslib==2.1.1
    - numpydoc==0.9.1
    - openpyxl==2.6.2
    - overrides==1.9
    - parsimonious==0.8.1
    - pathtools==0.1.2
    - pathy==0.6.0
    - plac==0.9.6
    - pluggy==0.12.0
    - preshed==3.0.6
    - protobuf==3.8.0
    - pyasn1==0.4.5
    - pyopenssl==19.0.0
    - pyrsistent==0.15.2
    - requests==2.22.0
    - responses==0.10.6
    - rsa==3.4.2
    - s3transfer==0.2.1
    - sacremoses==0.0.53
    - scispacy==0.4.0
    - sentencepiece==0.1.96
    - simplejson==3.16.0
    - smart-open==5.2.1
    - snowballstemmer==1.2.1
    - sortedcontainers==2.1.0
    - spacy-langdetect
    - sphinx
    - sqlalchemy==1.0.8
    - sqlparse==0.3.0
    - srsly==2.4.2
    - tensorboardx==1.7
    - tokenizers==0.9.2
    - transformers==3.4.0
    - unidecode
    - watchdog
    - wcwidth
    - websocket-client
    - werkzeug
    - word2number

